include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    always_put_required_named_parameters_first: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
    - "**/build/**"
    - "**/.dart_tool/**"

linter:
  rules:
    # Enable additional strict rules
    prefer_single_quotes: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_typing_uninitialized_variables: true
    use_build_context_synchronously: true
    avoid_void_async: true
    prefer_void_to_null: true
    avoid_dynamic_calls: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    # Disable some rules that might be too strict
    public_member_api_docs: false
    avoid_catches_without_on_clauses: false
